spring:
  application:
    name: slackclone

  datasource:
    url: jdbc:postgresql://localhost:5432/slack_clone
    username: siya
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true